### ISSUE TITLE
evx-generator is broken

### ISSUE THREAD

**Issue by horttanainen** [horttanainen/poker-eval#1]
Strange lines of Ís are formed where evx_preample.cfrag is glued to the generated table:
https://github.com/horttanainen/poker-eval/blob/master/poker-eval/inlines/evx5.h#L43
https://github.com/horttanainen/poker-eval/blob/master/poker-eval/inlines/evx7.h#L43

This happens in both master and attempt-to-convert-to-cpp branches.

**Comment by mpietarin** [comment]
Yup, the old "Unix opens files in binary mode and Windows opens them in textual mode by default". Probably the most annoying difference between those two worlds.
To fix do this (code works on both platforms):
  fp = fopen (path, "r");
==>
  fp = fopen (path, "rb");

**Comment by horttanainen** [comment]
:feelsgood: Great!
